In [1]:
import numpy as np
import pandas as pd
from pandas import read_sql, DataFrame
from sqlalchemy import create_engine

engine = create_engine(
    'mssql+pyodbc://sa:CgSqlServerRoot2012@172.17.18.110/cgyypt?driver=ODBC+Driver+17+for+SQL+Server')
with engine.connect() as db:
    data = read_sql('select * from wl_dwxx', db)

In [2]:
data.shape

(6967, 16)

In [17]:
top_unit:DataFrame = data.loc[data['sjid'] == 0].copy()
unit_child:DataFrame = data.loc[data['sjid'] != 0]
def get_unit_tree(data:DataFrame):
    unit_child_group = data.groupby(by='sjid')
    for k, v in unit_child_group:
        # print('k========',k)
        # print('v========',v['sjid'])

        if not top_unit.loc[top_unit['id'] == k].empty:
            top_unit.loc[top_unit['id'] == k, 'child_data'] = v.to_json(orient='records')


get_unit_tree(unit_child)

In [18]:
top_unit

,id,dwlbid,sjid,sfklb,sxs,dwdm,dwmc,dwmc_d,pym,dwdz,dwdz_d,lxdh,fzr,bz,sm,ty,child_data
0,1,2,0,2.0,1.0,02409,陈石春,None,CSC,,None,,,,,False,"[{""id"":99999,""dwlbid"":2,""sjid"":1,""sfklb"":2.0,""..."
1,2,2,0,2.0,2.0,9902,李春波,None,lcb,,None,,,,,False,NaN
2,3,2,0,2.0,3.0,01003,玉溪市乾鑫矿业有限公司,None,YXSQXKYYXG,,None,6456,,4564564565,,True,"[{""id"":1547100199988633600,""dwlbid"":2,""sjid"":3..."
3,4,2,0,2.0,4.0,01004,江西万舟再生资源有限公司（方永会）,None,jxwzzszyyx,,None,,,,,True,NaN
4,5,2,0,2.0,5.0,01005,昌伟,None,CW,,None,,,,,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6955,1547086240933879808,2,0,NaN,4.0,07024,测试单位8,None,None,None,None,None,None,None,None,False,NaN
6956,1547086245883158528,2,0,NaN,4.0,07024,测试单位8,None,None,None,None,None,None,None,None,False,"[{""id"":15,""dwlbid"":2,""sjid"":154708624588315852..."
6957,1547086256834486272,2,0,NaN,4.0,07024,测试单位8,None,None,None,None,None,None,None,None,False,NaN
6958,1547086260437393408,2,0,NaN,4.0,07024,测试单位8,None,None,None,None,None,None,None,None,False,NaN
6961,1547755948494430208,2,0,NaN,NaN,None,None,None,None,None,None,None,None,None,None,False,NaN

In [5]:
data['sjid'].value_counts()

0       5758
2130     322
4490      41
4494      40
4491      33
        ...
4565       1
4547       1
4523       1
2074       1
1764       1
Name: sjid, Length: 255, dtype: int64

In [6]:
group_data = data.groupby('sjid')

In [7]:
group_keys = group_data.groups.keys()

In [8]:
k = list(group_keys)

In [9]:
sj = data.loc[(data['id'].isin(k)) & (data['sjid'] != 0)]
sj

,id,dwlbid,sjid,sfklb,sxs,dwdm,dwmc,dwmc_d,pym,dwdz,dwdz_d,lxdh,fzr,bz,sm,ty
134,135,2,1490,2.0,135.0,02072,周刚生,None,zgs,,None,,,,,False
810,813,1,833,1.0,813.0,11202,越钢,None,YG,,None,,,,,True
815,818,1,3343,1.0,818.0,11207,金发平,None,JFP,,None,,,,,True
990,994,2,993,2.0,994.0,1112,彭德群,None,pdq,,None,,,,,False
1588,1688,2,1396,2.0,1688.0,1689,刘秦梅,None,lqm,,None,,,,,False
1691,1791,2,135,2.0,1791.0,10551,黄石市盛宝迪机械有限公司,None,hsssbdjxyx,,None,,,,,False
1760,1861,2,1471,2.0,1861.0,1861,营口宝拓冶金工业有限公司,None,ykbtyjgyyx,,None,,,,,False
1828,1955,2,1954,2.0,1955.0,1955,马龙县惠石建材,None,mlxhsjc,马龙县惠石建材,None,,,,,False
1924,2067,1,940,1.0,2067.0,1049,中国船舶工业物资云贵有限公司 友,None,zgcbgywzyg,,None,,,,,True
1983,2131,1,2130,1.0,2131.0,1102,海创 中奕 大理,None,hczydl,,None,,,,,True
1987,2135,1,2130,1.0,2135.0,10911,贵阳南 方筑 马龙,None,gynfzml,,None,,,,,True
2000,2149,1,2130,1.0,2149.0,2149,,None,,,None,,,,,True
2003,2152,1,942,1.0,2152.0,10905,彭钢,None,pg,,None,,,,,False
2012,2161,1,2130,1.0,2161.0,2161,郑存华,None,zch,,None,,,,,True
2013,2162,1,2130,1.0,2162.0,2162,昆明大汉公司,None,kmdhgs,,None,,,,,True
2015,2164,1,2130,1.0,2164.0,2164,云南兴特宸建筑工程有限公司,None,ynxtcjzgcy,,None,,,,,True
2027,2176,1,2130,1.0,2176.0,2157,福建恒源达投资有限公司 工程处,None,fjhydtzyxg,,None,,,,,True
2060,2222,1,2130,1.0,2222.0,2222,成都广盛隆 工程处,None,cdgslgcc,,None,,,,,True
2066,2228,1,940,1.0,2228.0,2230,木金 友,None,mjy,,None,,,,,False
2071,2235,1,1949,1.0,2235.0,2235,云南瑞增经贸有限公司,None,ynrzjmyxgs,,None,,,,,True
2184,2378,1,4478,1.0,2378.0,2378,上海畅雄物资有限公司 海 昆,None,shcxwzyxgs,,None,,,,,True
2225,2421,1,2130,1.0,2421.0,2421,马龙工地,None,mlgd,,None,,,,,True
2551,2836,1,2130,1.0,2836.0,2836,昆明时代之窗建设项目,None,kmsdzcjsxm,,None,,,,,True
2574,2882,1,2130,1.0,2882.0,2882,昭通彝良工地,None,ztylgd,,None,,,,,True
2618,2930,1,2164,1.0,2930.0,2930,贵州黔桂天能焦化有限公司,None,gzqgtnjhyx,贵阳花溪,None,,,,,True
2717,3097,1,2161,1.0,3097.0,3097,中国有色金属工业昆明勘察设计研究,None,zgysjsgykm,,None,,,,,True
2816,3215,1,2130,1.0,3215.0,99039,新增客户3215,None,,,None,,,,,True
2822,3221,1,2130,1.0,3221.0,99043,新增客户3221,None,,,None,,,,,True
2895,3297,1,2149,1.0,3297.0,3297,李连华,None,llh,,None,,,,,True
2941,3343,1,817,1.0,3343.0,3343,云南佳钢投资有限公司 佳,None,ynjgtzyxgs,,None,,,,,True
2998,3405,1,2130,1.0,3405.0,99092,新增客户3405,None,,,None,,,,,True
3003,3411,1,2130,1.0,3411.0,99095,新增客户3411,None,,,None,,,,,True
3133,3564,1,2836,1.0,3564.0,99117,新增客户3564,None,,,None,,,,,True
3136,3567,1,2836,1.0,3567.0,99119,新增客户3567,None,,,None,,,,,True
3362,3813,1,2130,1.0,3813.0,99142,新增客户3813,None,,,None,,,,,True
3363,3814,1,3813,1.0,3814.0,99143,新增客户3814,None,,,None,,,,,True
3411,3864,1,2130,1.0,3864.0,99161,新增客户3864,None,,,None,,,,,True
3414,3867,1,2130,1.0,3867.0,99163,新增客户3867,None,,,None,,,,,True
3577,4047,1,2130,1.0,4047.0,99243,新增客户4047,None,,,None,,,,,True
3697,4185,1,2130,1.0,4185.0,99254,新增客户4185,None,,,None,,,,,True
3717,4215,1,2130,1.0,4215.0,99267,新增客户4215,None,,,None,,,,,True
3726,4225,1,2130,1.0,4225.0,99272,新增客户4225,None,,,None,,,,,True
3733,4232,1,2130,1.0,4232.0,99279,新增客户4232,None,,,None,,,,,True
3734,4233,1,4232,1.0,4233.0,99280,新增客户4233,None,,,None,,,,,True
3851,4361,1,2130,1.0,4361.0,99333,新增客户4361,None,,,None,,,,,True
3855,4365,1,2130,1.0,4365.0,99338,新增客户4365,None,,,None,,,,,True
3859,4369,1,2130,1.0,4369.0,99342,新增客户4369,None,,,None,,,,,True
3862,4372,1,4369,1.0,4372.0,99344,新增客户4372,None,,,None,,,,,True
3913,4424,1,2130,1.0,4424.0,99376,新增客户4424,None,,,None,,,,,True
3914,4425,1,4424,1.0,4425.0,99377,新增客户4425,None,,,None,,,,,True
3942,4458,1,2130,1.0,4458.0,99393,新增客户4458,None,,,None,,,,,True
4001,4518,1,2130,1.0,4518.0,99425,新增客户4518,None,,,None,,,,,True
4002,4519,1,4518,1.0,4519.0,99426,新增客户4519,None,,,None,,,,,True
4006,4523,1,2130,1.0,4523.0,99429,新增客户4523,None,,,None,,,,,True
4027,4547,1,2130,1.0,4547.0,99433,新增客户4547,None,,,None,,,,,True
5225,5977,1,4954,1.0,5977.0,5977,云南省国有资本运营金鼎商业有限公司,None,ynsgyzbyyj,,None,,,,,True
6952,1547030419613032448,3,1547030419613032448,NaN,4.0,07024,tttttttttt,12e21e12e,12e,12e12e12e,21e,e21e,None,e12e,e12e,False

In [10]:
sj_group = sj.groupby('sjid')

In [11]:
sj_group_keys = list(sj_group.groups.keys())

In [12]:
child_sj = sj.loc[sj['id'].isin(sj_group_keys)]

In [13]:
child_sj

,id,dwlbid,sjid,sfklb,sxs,dwdm,dwmc,dwmc_d,pym,dwdz,dwdz_d,lxdh,fzr,bz,sm,ty
134,135,2,1490,2.0,135.0,02072,周刚生,None,zgs,,None,,,,,False
2000,2149,1,2130,1.0,2149.0,2149,,None,,,None,,,,,True
2012,2161,1,2130,1.0,2161.0,2161,郑存华,None,zch,,None,,,,,True
2015,2164,1,2130,1.0,2164.0,2164,云南兴特宸建筑工程有限公司,None,ynxtcjzgcy,,None,,,,,True
2551,2836,1,2130,1.0,2836.0,2836,昆明时代之窗建设项目,None,kmsdzcjsxm,,None,,,,,True
2941,3343,1,817,1.0,3343.0,3343,云南佳钢投资有限公司 佳,None,ynjgtzyxgs,,None,,,,,True
3362,3813,1,2130,1.0,3813.0,99142,新增客户3813,None,,,None,,,,,True
3733,4232,1,2130,1.0,4232.0,99279,新增客户4232,None,,,None,,,,,True
3859,4369,1,2130,1.0,4369.0,99342,新增客户4369,None,,,None,,,,,True
3913,4424,1,2130,1.0,4424.0,99376,新增客户4424,None,,,None,,,,,True
4001,4518,1,2130,1.0,4518.0,99425,新增客户4518,None,,,None,,,,,True
6952,1547030419613032448,3,1547030419613032448,NaN,4.0,07024,tttttttttt,12e21e12e,12e,12e12e12e,21e,e21e,None,e12e,e12e,False

In [14]:
child_group = child_sj.groupby('sjid')

In [15]:
child_group_keys = list(sj_group.groups.keys())
child_sj.loc[child_sj['id'].isin(child_group_keys)]

,id,dwlbid,sjid,sfklb,sxs,dwdm,dwmc,dwmc_d,pym,dwdz,dwdz_d,lxdh,fzr,bz,sm,ty
134,135,2,1490,2.0,135.0,02072,周刚生,None,zgs,,None,,,,,False
2000,2149,1,2130,1.0,2149.0,2149,,None,,,None,,,,,True
2012,2161,1,2130,1.0,2161.0,2161,郑存华,None,zch,,None,,,,,True
2015,2164,1,2130,1.0,2164.0,2164,云南兴特宸建筑工程有限公司,None,ynxtcjzgcy,,None,,,,,True
2551,2836,1,2130,1.0,2836.0,2836,昆明时代之窗建设项目,None,kmsdzcjsxm,,None,,,,,True
2941,3343,1,817,1.0,3343.0,3343,云南佳钢投资有限公司 佳,None,ynjgtzyxgs,,None,,,,,True
3362,3813,1,2130,1.0,3813.0,99142,新增客户3813,None,,,None,,,,,True
3733,4232,1,2130,1.0,4232.0,99279,新增客户4232,None,,,None,,,,,True
3859,4369,1,2130,1.0,4369.0,99342,新增客户4369,None,,,None,,,,,True
3913,4424,1,2130,1.0,4424.0,99376,新增客户4424,None,,,None,,,,,True
4001,4518,1,2130,1.0,4518.0,99425,新增客户4518,None,,,None,,,,,True
6952,1547030419613032448,3,1547030419613032448,NaN,4.0,07024,tttttttttt,12e21e12e,12e,12e12e12e,21e,e21e,None,e12e,e12e,False